use std::collections::HashMap;

use sonorust_bytecode::{
    compiler::{CompilationResult, Compiler},
    ir_builder::IRBuilder,
    ir_parser::parse_script,
};

fn main() {
    let (_, stmts) = parse_script(
        r#"
temp_mem_block_id = 10000.0;
counter_mem_index = 0.0;
value_mem_index = 1.0;

get_counter = get(temp_mem_block_id, counter_mem_index);
get_value = get(temp_mem_block_id, value_mem_index);
counter_less_5 = less(get_counter, 5.0);

zero = 0.0;
one = 1.0;
incremented_counter = add([get_counter, one]);
incremented_value = add([get_value, one]);
increment_counter = set(temp_mem_block_id, counter_mem_index, incremented_counter);
increment_value = set(temp_mem_block_id, value_mem_index, incremented_value);
reset_counter = set(temp_mem_block_id, counter_mem_index, zero);

increment_loop_body = execute([increment_value, increment_counter]);
increment_loop = while(counter_less_5, increment_loop_body);

result = execute([increment_loop, reset_counter, get_value]);
return result;
        "#,
    )
    .unwrap();

    let mut ir_builder = IRBuilder::new();
    for stmt in stmts {
        ir_builder.lower_statement(stmt);
    }
    let (root_index, nodes) = ir_builder.finish();

    println!("{}", serde_json::to_string_pretty(&nodes).unwrap());

    let mut compiler = Compiler::new(&nodes);
    compiler.compile_node(root_index);
    let CompilationResult {
        instructions,
        basic_blocks,
        labels,
    } = compiler.finish();

    let basic_blocks: HashMap<_, _> = basic_blocks
        .iter()
        .cloned()
        .flat_map(|bb| [(bb.start_pc, bb.clone()), (bb.end_pc, bb)])
        .collect();

    println!("--- Generated Bytecode ---");
    for (i, op) in instructions.iter().enumerate() {
        if let Some(bb) = basic_blocks.get(&i) {
            if let Some(label) = labels.get(&i) {
                println!("{}: ({}-{})", label, bb.start_pc, bb.end_pc)
            } else {
                println!("unlabeled: ({}-{})", bb.start_pc, bb.end_pc);
            }
        }
        println!("{:04}: {:?}", i, op);
    }
    println!("--------------------------\n");

    // let mut vm = VM::new(2, 4);

    // vm.load_bytecode(&compiler.bytecode);
    // vm.run(10000);

    // println!("Final VM Stack State: {:#?}", vm.stack);
    // println!("Final VM Memory: {:#?}", vm.runtime_ctx);
}
